schedules:
  - cron: '0 7 * * 0-4'
    displayName: 'Daily morning build except for Friday and Saturday'
    branches:
      include:
        - '*dev*'

pool:
  vmImage: 'ubuntu-22.04'

jobs:
- job: hello_world
  steps:
    - bash: echo "Hello world! Have a good day"
- job: search_logs
  displayName: 'Search for ERROR in files ending with log in all branches containing the word dev'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        #!/bin/bash

        dev_dirs=$(find . -type d -name "*dev*")

        # Check if dev_dirs is empty
        if [ -z "$dev_dirs" ]; then
          echo "ERROR: No directories containing 'dev' found"
          exit 1
        fi

        found_error=false

        for dev_dir in $dev_dirs; do
          if $found_error; then
            break
          fi
          abs_dev_dir=$(realpath "$dev_dir" 2>/dev/null)
          cd "$abs_dev_dir" 2>/dev/null
          log_files=$(find . -type f -name "*log")
          for log_file in $log_files; do
              count=$(grep "ERROR" "$log_file" | wc -l)
              if [ "$count" -gt 0 ]; then
                  echo "FAIL found in $log_file"
                  found_error=true
                  break
              fi
          done
          cd ..
        done

        if ! $found_error; then
          echo "PASS"
        fi
- job: print_to_ERROR_log_file
  dependsOn: search_logs
  
  steps:
  - task: PythonScript@0
    displayName: 'Find all files that end in log inside the branches containing the word dev in their name and print to a txt file'
    condition: contains(variables['search_logs.task.stdout'], 'FAIL')
    inputs:
      versionSpec: '2.7.5'
      scriptSource: 'inline'
      script: |
          import os
  
          def search_for_error():
              error_log_files = []
  
              root_dir = os.getcwd().replace('\\', '/')                                       #get workspace directory, the search will 
                                                                                              #start from here, given each branch is a directory
  
              for dirpath, dirnames, filenames in os.walk(root_dir):                          #iterate over all directories that contain the word "dev" in their name
                  for dirname in dirnames:
                      if "dev" in dirname:
                          current_dir = os.path.join(dirpath, dirname)                        #get full path to the current directory               
                          for filename in os.listdir(current_dir):                            #iterate over all files in the current directory
                              if filename.endswith("log"):
                                  log_file_path = os.path.join(current_dir, filename)         #get the full path to the current log file
  
                                  with open(log_file_path, "r") as log_file:                  #check if the log file contains the word "ERROR"
                                      if "ERROR" in log_file.read():
                                          error_log_files.append(log_file_path)               #add the path to the to the list
  
              with open("log_files_with_error.txt", "w") as f:                                #overwrite the data to a file that saves all
                  for error_log_file in error_log_files:                                      #the error logs
                      f.write(error_log_file + "\n")
        
          search_for_error()